### ISSUE TITLE
Create new pages for apprenticeships data

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/WNYCC-LSIP#44]
New data available for these new visualisations in `data/csv/apprenticeships`.

Data is highly suppressed at a granular level (where `low >0 & <5`) but should be useful at higher aggregations (e.g. where `ssa_t1_level == 'Total'` or `apprenticeship_level == 'Total'`) and may still be useful to present the low data as a sign of small volumes.

More background info available in #32.

**Comment by gilesdring** [comment]
Start with 

* all subject / all level by LA - Hexmap of starts / achievements
* Try all subject (Total) by level / geo.
* Try all level by subject / geo.

**Comment by luke-strange** [comment]
All of the above is complete and can be seen at https://open-innovations.github.io/WNYCC-LSIP/wycc/supply/apprenticeships/ . For the subject area breakdown, many subjects had "low" entries. Since there were 13 subjects this became very ugly to look at with many different colours and very thin bars. After a chat with @gilesdring we have omitted "low" entries for now by setting them to 0 in the `prepare.py` script. I will email the client to check if they are happy with this decision.

**Comment by luke-strange** [comment]
Want to make bullet points in line - have had a play around but have not managed to get a working solution.

**Comment by gilesdring** [comment]
I think this looks good to go.
