### ISSUE TITLE
Process view data for further education

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#5]
see here for example vis https://www.insight-unlocked.co.uk/leicester-and-leicestershire/further-education-dashboard.html

**Comment by luke-strange** [comment]
List of stuff to find/calculate:

FE is study after secondary education which is not part of HE. Includes 3 types of technical and applied qualifications

**FE TRAINING**
-an achievement to enrolment ratio by LA. (assuming this means people who graduated/passed course vs initially signed up
-number entering FE by subject area
-number completing FE by subject area
(for the above two they have shown ratios with size (which btw is rubbish because you can't easily compare the area of different shaped rectangles by eye), we should just do %.)
-total students in Aims enrolments and aims achievements.

**FE basic skills**
-number in FE by subject area
-number completing FE by subject area
-achievement to participation % by LA.

**Comment by luke-strange** [comment]
Are "basic skills including/excluding digital skills" separate data or is one a subset of the other?

**Comment by luke-strange** [comment]
We might want to think about per capita figures if we can’t get decent student numbers.

**Comment by luke-strange** [comment]
need to discuss what to do about "low" values. for now they are set to 0.

**Comment by luke-strange** [comment]
there is a csv file Education and training geography - local authority district.csv which has many breakdowns by gender/ethnicity/subject area. we need discussion over what best to include. can we write code to make this selectable on the website?

**Comment by luke-strange** [comment]
![Image](https://user-images.githubusercontent.com/92686634/227194222-45542e54-2edb-44c7-9167-c3e94aaa1383.png)
